name: FIRE
channels:
  - conda-forge
dependencies:
  - python=3.11
  - loguru=0.7.2
  - numpy=1.26.2
  - pygments=2.15.1
  - matplotlib=3.8.0
  - tqdm=4.65.0
  - levenshtein=0.23.0
  - networkx=3.2.1
  - redis-py=5.0.1
  - flask=3.0.0
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pytorch::torchaudio=2.1.0
  - transformers=4.36.2
  - tree_sitter=0.20.4
  - anytree=2.8.0
  - pip
  - pip:
    - bloom-filter2==2.0.0
    - ppdeep==20200505
